### PR TITLE
Wrap update_files calls in conditionals

### LINKED ISSUE #144: cypress-on-rails gem Error: File unchanged! The supplied flag value not found! cypress/support/index.js
while running this cmd in rails terminal
**rails g cypress_on_rails:install
i got this error**
myProject/playwright/support/index.js does not appear to exist

it unable to find **index.js** and **playwright** folder never exist????

cypress folder created by this command itself does not have **playwright** folder, but **have index.js** in myProject/support/index.js

Any solution???
**here is log**

create cypress/support/index.js
create cypress/support/commands.js
create cypress.config.js
identical config/initializers/cypress_on_rails.rb
identical e2e/e2e_helper.rb
exist e2e/app_commands
identical e2e/app_commands/activerecord_fixtures.rb
identical e2e/app_commands/clean.rb
identical e2e/app_commands/eval.rb
identical e2e/app_commands/factory_bot.rb
identical e2e/app_commands/log_fail.rb
identical e2e/app_commands/scenarios/basic.rb
create cypress/support/on-rails.js
create cypress/e2e/rails_examples
create cypress/e2e/rails_examples/advance_factory_bot.cy.js
create cypress/e2e/rails_examples/other.cy.js
create cypress/e2e/rails_examples/using_factory_bot.cy.js
create cypress/e2e/rails_examples/using_fixtures.cy.js
create cypress/e2e/rails_examples/using_scenarios.cy.js
create cypress/e2e/rails_examples/using_vcr.cy.js
**File unchanged! The supplied flag value not found! cypress/support/index.js
The file /path/playwright/support/index.js does not appear to exist**

### PR DESCRIPTION
**Pull request by Judahmeek**
Should resolve #144

### CODE REVIEW

File: lib/generators/cypress_on_rails/install_generator.rb [hunk 1]
```diff
@@ -57,12 +57,16 @@ def add_initial_files
     end
 
     def update_files
+      if options.install_cypress
       append_to_file "#{options.cypress_folder}/support/index.js",
                      "\nimport './on-rails'",
                      after: 'import \'./commands\''
```
Comment (Judahmeek) [inline lib/generators/cypress_on_rails/install_generator.rb:63]: @grantspeelman is this line even necessary considering the [code that it wants to append](https://github.com/shakacode/cypress-on-rails/blob/master/lib/generators/cypress_on_rails/install_generator.rb#L61) appears to now be [a default part of the file](https://github.com/shakacode/cypress-on-rails/blob/master/lib/generators/cypress_on_rails/templates/spec/cypress/support/index.js.erb#L19)

**Comment by grantspeelman** [comment]
thanks @Judahmeek for picking this up 👍🏽
